### ISSUE TITLE
Test on AWS Graviton

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#1040]
https://aws.amazon.com/ec2/graviton/

> Free Trial: Until Dec 31st 2020, all new and existing AWS customers can try the t4g.micro instances free for up to 750 hours per month. During the free-trial period, customers who run a t4g.micro instance will automatically get 750 free hours per month deducted from their monthly bill through Dec 2020.

https://aws.amazon.com/ec2/faqs/#t4g-instances

We expect the test to fail before additional work has been done in the Client team.

**Comment by divyenduz** [comment]
Which job does this one belong in? I would think `binaries` but that runs on all OSes. Putting this in platforms at the moment but we can move it around later.

**Comment by divyenduz** [comment]
Unassigned because PR with failing test is done and the PR can't be merged before this binary is implemented.
