### ISSUE TITLE
Clean up upgrade scripts

### ISSUE THREAD

**Issue by divyenduz** [prisma/ecosystem-tests#1112]
`check-for-update` script does a lot

- The `check-for-update` script does long polling to quickly bump Prisma versions https://github.com/prisma/e2e-tests/blob/dev/.github/scripts/check-for-update.sh#L47-L55 (creates a loop)
- The loop calls run_sync https://github.com/prisma/e2e-tests/blob/dev/.github/scripts/check-for-update.sh#L104
- Run sync force pushes https://github.com/prisma/e2e-tests/blob/dev/.github/scripts/sync.sh#L36-L37
- much more

This makes the script difficult to read and debug when something goes wrong. A recent issue when `@prisma/cli` was incorrectly in `dependencies` instead of `devDependencies` caused an explosion of CI jobs

We need to fundamentally re-think this script, make it more efficient/readable. 

This issue tracks defining and implementing it

**Comment by millsp** [comment]
Now fixed in the new pnpm setup.
