### ISSUE TITLE
Heroku Connection Pooling

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#1317]
This exists now:
https://blog.heroku.com/connection-pooling
https://devcenter.heroku.com/articles/postgres-connection-pooling

We should test this.

**Comment by janpio** [comment]
How is this different from https://github.com/prisma/e2e-tests/tree/dev/databases/heroku-pgbouncer? Should be added to README there.

**Comment by Jolg42** [comment]
Looks like there is also a client side `on dyno` version https://devcenter.heroku.com/articles/on-dyno-postgres-connection-pooling (Older solution I guess)

**Comment by janpio** [comment]
> Looks like there is also a client side `on dyno` version [devcenter.heroku.com/articles/on-dyno-postgres-connection-pooling](https://devcenter.heroku.com/articles/on-dyno-postgres-connection-pooling) (Older solution I guess)

Yes, as far as I know that is the same thing we are testing with https://github.com/prisma/e2e-tests/tree/dev/databases/heroku-pgbouncer-buildpack

**Comment by divyenduz** [comment]
This is the same as https://github.com/prisma/e2e-tests/tree/dev/databases/heroku-pgbouncer
It got out of beta.
