### ISSUE TITLE
Fix unexpected files that were added via #1318

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#1360]
In https://github.com/prisma/e2e-tests/pull/1318 somehow a _lot_ if new files got added to the codebase. Looks like some bundler ran or similar on the whole codebase. All these files should not be part of the codebase and that PR.

A list (which might not be complete):

---

https://github.com/prisma/e2e-tests/pull/1318/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.sh#diff-86c546d65f42647facb573a3407292719e756e2f8b54ef3fcdf72e32522c8ce4

- generic/basic/script.js 
---
https://github.com/prisma/e2e-tests/pull/1318/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.sh#diff-d091b65f5216aa41dff2f91839ac7f2e1220582b301d16766e050ee567560037

- frameworks/nestjs/src/app.controller.js 
- frameworks/nestjs/src/app.controller.spec.js
-  frameworks/nestjs/src/app.module.js
-  frameworks/nestjs/src/app.service.js
- frameworks/nestjs/src/main.js 
-  frameworks/nestjs/src/prisma.service.js
-  frameworks/nestjs/test/app.e2e-spec.js 
-  frameworks/nextjs/pages/index.js

---
https://github.com/prisma/e2e-tests/pull/1318/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.sh#diff-c8e2169f00714f2a5a7e5df7020a57a26e730ead5181c24cf0ca9318d5c2340c

- core-features/browser-build/components/browser-build.js 
- core-features/browser-build/pages/index.js

--- 

https://github.com/prisma/e2e-tests/pull/1318/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.sh#diff-47500f74abc652db174cd4e00d295f484c983a32908df633bdf015a9fe5ed248

- libraries/apollo-server/src/context.js 
- libraries/apollo-server/src/server.js

---

https://github.com/prisma/e2e-tests/pull/1318/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.sh#diff-c3f715905112e90eed509eae93d427b59ec03fbed0e63606a4b6d37676613360

- libraries/express/src/index.js 

---

https://github.com/prisma/e2e-tests/pull/1318/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.sh#diff-ef1a9a689caa49571634eef4601b6df732dc596ee1f5069c84562afe13cc71d5

- libraries/nexus-schema/src/context.js
- libraries/nexus-schema/src/schema.js
-  libraries/nexus-schema/src/server.js

---

- libraries/type-graphql/index.js 
- libraries/type-graphql/test-resolver.js

---

- packagers/npm/script.js

---

Not separating by project any more after this:

- packagers/yarn-workspaces/prisma-project/script.js 
-  packagers/yarn/script.js
- packagers/yarn2-without-pnp/script.js
- platforms/codesandbox/deploy.js
-  test-runners/jest-with-multiple-generators/main.js
- test-runners/jest-with-multiple-generators/src/__tests__/the.test.js
- utils/fetch-retry.js

**Comment by divyenduz** [comment]
Fixed via https://github.com/prisma/e2e-tests/pull/1362
