### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by divyenduz** [prisma/ecosystem-tests#1407]
This issue contains a list of Renovate updates and their statuses.

## Rate Limited

These updates are currently rate limited. Click on a checkbox below to force their creation now.

 - [ ] chore(deps): update dependency aws-sdk to v2.842.0 (dev)
 - [ ] chore(deps): update dependency webpack to v5.21.2 (dev)
 - [ ] chore(deps): update typescript-eslint monorepo to v4.15.0 (dev) (`@typescript-eslint/eslint-plugin`, `@typescript-eslint/parser`)
 - [ ] fix(deps): update @redwoodjs packages to v0.25.0 (dev) (`@redwoodjs/api`, `@redwoodjs/core`, `@redwoodjs/forms`, `@redwoodjs/router`, `@redwoodjs/web`)
 - [ ] fix(deps): update dependency @types/express to v4.17.11 (dev)
 - [ ] fix(deps): update dependency apollo-server to v2.20.0 (dev)
 - [ ] fix(deps): update dependency fetch-retry to v4.1.0 (dev)
 - [ ] fix(deps): update dependency firebase-admin to v9.5.0 (dev)
 - [ ] fix(deps): update nest monorepo to v7.6.12 (dev) (`@nestjs/common`, `@nestjs/core`, `@nestjs/platform-express`, `@nestjs/testing`)
 - [ ] fix(deps): update prisma monorepo to v2.17.0-integration-postinstall-test.10 (dev) (`@prisma/client`, `prisma`)
 - [ ] chore(deps): update dependency netlify-cli to v3 (dev)
 - [ ] fix(deps): update dependency @slack/webhook to v6 (dev)
 - [ ] fix(deps): update dependency puppeteer to v7 (dev)
 - [ ] chore(deps): update amannn/action-semantic-pull-request action to v3.3.0 (dev2)
 - [ ] chore(deps): update dependency @types/node to v12.19.16 (dev2)
 - [ ] chore(deps): update dependency aws-sdk to v2.842.0 (dev2)
 - [ ] chore(deps): update dependency ts-loader to v8.0.17 (dev2)
 - [ ] chore(deps): update dependency ts-node to v9.1.1 (dev2)
 - [ ] chore(deps): update dependency typegraphql-prisma to v0.10.3 (dev2)
 - [ ] chore(deps): update dependency typescript to v4.1.5 (dev2)
 - [ ] chore(deps): update dependency webpack to v5.21.2 (dev2)
 - [ ] fix(deps): update @redwoodjs packages to v0.25.0 (dev2) (`@redwoodjs/api`, `@redwoodjs/core`, `@redwoodjs/forms`, `@redwoodjs/router`, `@redwoodjs/web`)
 - [ ] fix(deps): update dependency @types/express to v4.17.11 (dev2)
 - [ ] fix(deps): update dependency apollo-server to v2.20.0 (dev2)
 - [ ] fix(deps): update dependency fetch-retry to v4.1.0 (dev2)
 - [ ] fix(deps): update dependency firebase-admin to v9.5.0 (dev2)
 - [ ] fix(deps): update nest monorepo to v7.6.12 (dev2) (`@nestjs/common`, `@nestjs/core`, `@nestjs/platform-express`, `@nestjs/testing`)
 - [ ] fix(deps): update prisma monorepo to v2.17.0-dev.52 (dev2) (`@prisma/client`, `prisma`)
 - [ ] chore(deps): update dependency netlify-cli to v3 (dev2)
 - [ ] fix(deps): update dependency @slack/webhook to v6 (dev2)
 - [ ] fix(deps): update dependency puppeteer to v7 (dev2)

## Edited/Blocked

These updates have been manually edited so Renovate will no longer make changes. To discard all commits and start over, check the box below.

 - [ ] chore(deps): update typescript-eslint monorepo to v4.15.0 (dev2) (`@typescript-eslint/eslint-plugin`, `@typescript-eslint/parser`)

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [chore(deps): update amannn/action-semantic-pull-request action to v3.3.0 (dev)](../pull/1405)
 - [ ] [chore(deps): update dependency @types/node to v12.19.16 (dev)](../pull/1406)
 - [ ] [chore(deps): update dependency ts-loader to v8.0.17 (dev)](../pull/1408)
 - [ ] [chore(deps): update dependency ts-node to v9.1.1 (dev)](../pull/1409)
 - [ ] [chore(deps): update dependency typegraphql-prisma to v0.10.3 (dev)](../pull/1410)
 - [ ] [chore(deps): update dependency typescript to v4.1.5 (dev)](../pull/1411)
 - [ ] **Check this option to rebase all the above open PRs at once**

**Comment by janpio** [comment]
This was an experiment with local Renovate.
