### ISSUE TITLE
Remove not needed dependencies

### ISSUE THREAD

**Issue by Jolg42** [prisma/ecosystem-tests#1671]
https://github.com/prisma/e2e-tests/blob/a53b0cf14865c111c03ccc536434ca221300eecc/platforms-serverless/firebase-functions/functions/package.json

**Comment by janpio** [comment]
Why was it there in the first place? Maybe required to setup projects in the beginning or similar?

**Comment by Jolg42** [comment]
Maybe part of the default setup / tutorial 🤷

**Comment by Jolg42** [comment]
Also rxjs seems extra to me https://github.com/prisma/e2e-tests/blob/7b112f4845812789a9ff7b0d4ee3a94a6a59c1d5/frameworks/nestjs/package.json#L30

**Comment by janpio** [comment]
The NestJS project is a default project I think, generated and just put in here (at least it was in the past).
