### ISSUE TITLE
Add netlify-ci test with netlify build image Ubuntu 20.04 Focal Fossa

### ISSUE THREAD

**Issue by Jolg42** [prisma/ecosystem-tests#1772]
We will need to duplicate the current netlify-ci test and select the image like here
https://app.netlify.com/sites/prisma2-e2e-tests-netlify-ci/settings/deploys
<img width="528" alt="Screen Shot 2021-06-09 at 14 23 54" src="https://user-images.githubusercontent.com/1328733/121353959-b490d000-c92e-11eb-8cf7-7383888a9ec6.png">

It's possible we need to update these
https://github.com/prisma/prisma/blob/d171f8fd39ecead293ea85afe38578c10dd47102/src/packages/client/src/generation/generateClient.ts#L254-L255
https://github.com/prisma/prisma/blob/d171f8fd39ecead293ea85afe38578c10dd47102/src/packages/client/src/generation/utils.ts#L373-L375

Because I think we would need to have `rhel-openssl-1.1.x` for that new Ubuntu version.
More info about new Ubuntu version can be found in https://github.com/netlify/build-image/releases

**Comment by janpio** [comment]
This now already builds on Ubuntu Focal 20.04 (default)
