### ISSUE TITLE
Test pnpm

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#1804]
[pnpm](https://pnpm.io/) has this nice recursive `install` and `update` command that we could use to easily upgrade all sub projects in this repository with 1 command. 

Installation commands in CI/test scripts etc could (or might need to) be adapted, but potentially we can also keep using `yarn` for these as we do not rely on lockfiles or existing `node_modules` folders when running our scripts. Then `pnpm` really would just be used when managing the dependencies via the scripts that interact with all projects (basically: updating Prisma dependencies).

**Comment by millsp** [comment]
Done via new pnpm setup.
