### ISSUE TITLE
Use yarn resolutions for redwood dependency override

### ISSUE THREAD

**Issue by millsp** [prisma/ecosystem-tests#1921]
Internal https://prisma-company.slack.com/archives/CL0AJEVSA/p1625882635040500

**Comment by janpio** [comment]
Should already be possible in the update script as we were using that before.

If we can avoid it, we should though as it doubles the complexity and was a source of endless problems in the past.

**Comment by Jolg42** [comment]
Note: we currently use the override in 
https://github.com/prisma/ecosystem-tests/blob/dev/platforms-serverless-vercel/vercel-with-redwood/api/package.json#L9-L12
https://github.com/prisma/ecosystem-tests/blob/dev/platforms-serverless-vercel/vercel-with-redwood/package.json#L16-L19

And we have this script (https://github.com/prisma/ecosystem-tests/blob/dev/platforms-serverless-vercel/vercel-with-redwood/patch-package-json.js
) that seems to update the version with the version from
https://github.com/prisma/ecosystem-tests/blob/dev/.github/prisma-version.txt

**Comment by Jolg42** [comment]
We now have an issue about check-for-update doesn't bump resolutions in package.json -> https://github.com/prisma/ecosystem-tests/issues/3041
