### ISSUE TITLE
Redwood project, `api` subproject is ignored in update script, listing old Prisma version

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#1951]
https://github.com/prisma/e2e-tests/blob/91994e43826960f0f3ca1d97c2d07944e5292fa0/platforms-serverless/vercel-with-redwood/api/package.json#L5-L11

after https://github.com/prisma/e2e-tests/pull/1950

**Comment by Jolg42** [comment]
The issue is now different, as we switched to yarn `resolutions` https://github.com/prisma/ecosystem-tests/blob/dev/platforms-serverless-vercel/vercel-with-redwood/api/package.json

I created a more relevant issue https://github.com/prisma/ecosystem-tests/issues/3041
