### ISSUE TITLE
Make Vercel jobs wait for at least the time the CLI returns on API rate limit events

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#2728]
Our Vercel jobs sometimes hit API rate limits. The CLI responses include some information how long we should wait until we try again, but we are not using that information in our retry logic right now and instead retry pretty much instantly. This of course makes he problem worse.

```
Error! You have been creating deployments at a very fast pace. Please retry in 38 seconds.
```

Potential approach: Get strerr output in a file, parse it in `finally.sh` with a regex and then wait for x seconds before letting the script run the next retry.

**Comment by Jolg42** [comment]
We do not have this issue anymore since our rate limit was uplifted.

**Comment by janpio** [comment]
The problem still exists fundamentally - if we hit any API limits, the script will try again instantly.

**Comment by Jolg42** [comment]
Sure, we do not need to do anything here, though. Since we do not see this issue anymore.

**Comment by janpio** [comment]
🤞
