### ISSUE TITLE
Optional tests are always run although no changes in files

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#2809]
See https://github.com/prisma/ecosystem-tests/pull/2808
<img width="726" alt="image" src="https://user-images.githubusercontent.com/183673/170019496-490b273f-803f-483a-8a27-1597b5a993f0.png">

**Comment by Jolg42** [comment]
Something we can probably handle with https://github.com/prisma/ecosystem-tests/blob/dev/.github/workflows/detect-jobs-to-run.js
