### ISSUE TITLE
Pass the functional tests on the Data Proxy

### ISSUE THREAD

**Issue by millsp** [prisma/ecosystem-tests#2874]
We are not testing that *all* queries work as expected via the data proxy. I think it would be worth checking that via an ecosystem test. Basically, I'd like to run our `test:functional:code` tests from `prisma/prisma` against the Data Proxy. We could try multi-provider, but probably doing a single provider is more than enough.

**Comment by Jolg42** [comment]
@millsp Is this still relevant? Now that there is a "mini-proxy" approach?

**Comment by millsp** [comment]
I think we can close this, thanks!
