### ISSUE TITLE
check-for-update doesn't bump `resolutions` in package.json

### ISSUE THREAD

**Issue by Jolg42** [prisma/ecosystem-tests#3041]
We implemented something that looks like we handle `resolutions` and update prisma dependencies versions here
https://github.com/prisma/ecosystem-tests/blob/88e5bca3b7cd63dd7cd5e623ac3a3953274328e2/.github/scripts/check-for-update.sh#L105-L131

Though `resolutions` for the `[vercel-with-redwood](https://github.com/prisma/ecosystem-tests/tree/dev/platforms-serverless-vercel/vercel-with-redwood)` directory were not updated since a long time and I did it manually in:
https://github.com/prisma/ecosystem-tests/pull/3004

We should check if there is a bug in `check-for-update.sh` logic.

**Comment by millsp** [comment]
Fixed in the new pnpm setup.
