### ISSUE TITLE
Split out expected failing tests from optional tests so it is clearer that they are expected to fail

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#3351]

**Comment by Jolg42** [comment]
@janpio Are you talking about the cosmosdb test only here?
<img width="270" alt="Screenshot 2023-01-18 at 13 27 16" src="https://user-images.githubusercontent.com/1328733/213171325-59e0bec0-abf7-4f8e-adc6-8a797901ccc0.png">

https://github.com/prisma/ecosystem-tests/actions/runs/3947611630

**Comment by janpio** [comment]
Yes, at this time.
