### ISSUE TITLE
Move `DP2_ITX_PDP_MONGODB` and `DP2_ITX_PDP_MONGODB_DATABASE_URL` from org secret to repo secret

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#3944]
Follow up to https://github.com/prisma/ecosystem-tests/pull/3939/files

**Comment by Jolg42** [comment]
Let's wait at least one week to do this, as it would fail the tests if we do a patch release, as `patch-dev` is behind these commits
