### ISSUE TITLE
Simplify Nestjs e2e test

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#597]
The current e2e test is built on https://github.com/fivethree-team/nestjs-prisma-starter
Because of that it uses a lot of unused dependencies and adds complexity that is not necessary (and leads to unmergable security fixes like https://github.com/prisma/e2e-tests/pull/392 and https://github.com/prisma/e2e-tests/network/alert/frameworks/nestjs/yarn.lock/apollo-server-express/open)

The project could easily be replaced by a project based on https://github.com/nestjs/typescript-starter. The whole logic around the e2e test (run, test, the logic) can just be copied over.

**Comment by divyenduz** [comment]
This was done in https://github.com/prisma/e2e-tests/pull/982
