### ISSUE TITLE
Explicitly set `CI=1` on all systems we run the CLI in any form

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#635]
Github Actions, but also all the providers and hosts etc.

**Comment by divyenduz** [comment]
Task list: 

General: 

- [x] Add `CI=1` to GH Action @divyenduz https://github.com/prisma/e2e-tests/pull/670

Tests where `yarn install` might be running: 

- [x] platforms/azure-functions-linux @steebchen no remote cli
- [x] platforms/azure-functions-windows @steebchen no remote cli
- [x] platforms/firebase-functions @steebchen https://github.com/prisma/e2e-tests/pull/669
- [x] platforms/gcp-functions @steebchen https://github.com/prisma/e2e-tests/pull/669
- [x] platforms/heroku @divyenduz 
- [x] platforms/lambda @steebchen no remote cli
- [x] platforms/netlify-beta-ci @divyenduz 
- [x] platforms/netlify-current-cli @divyenduz 
- [x] platforms/serverless-lambda @steebchen no remote cli
- [x] platforms/vercel-api @divyenduz 
- [x] platforms/vercel-node-builder @divyenduz 
- [x] databases/heroku-pgbouncer @divyenduz 
- [x] databases/heroku-pgbouncer-buildpack @divyenduz
