### ISSUE TITLE
.editorconfig overrides prettier defaults

### ISSUE THREAD

**Issue by divyenduz** [prisma/ecosystem-tests#689]
Since the addition of this https://github.com/prisma/e2e-tests/blob/dev/.editorconfig

Prettier doesn't follow the workspace settings. I want 3 settings to be specific

1. Trailing comma = all
2. Semi = false
3. Single quote = true

![image](https://user-images.githubusercontent.com/746482/90013480-f62afd00-dcc2-11ea-8c00-d5b7ac1b7658.png)

Why was this added though @steebchen? I can try and adjust this prettier config in this file.

**Comment by divyenduz** [comment]
I see that I can do 

`quote_type = single`

But I couldn't find anything for trailing comma, semicolons. I will see if I can make prettier ignore this but this file breaks my workflow.

**Comment by divyenduz** [comment]
I can fix this with a top-level `.prettierrc` file. Let's lock style guide before I make a PR for this. 

```
divyendusingh [e2e-tests]$ cat .prettierrc
{
  "semi": false,
  "singleQuote": true,
  "trailingComma": "all"
}
```

**Comment by steebchen** [comment]
I just added the editor config to ensure 2 spaces and no white space. I don't understand how it interferes with the prettier config

**Comment by divyenduz** [comment]
Prettier tries to read it and merge it with its own config.

**Comment by steebchen** [comment]
but that should work, right? is there anything different for the rules specified in prettier?

**Comment by divyenduz** [comment]
No, from these three, I couldn't find how to set `semi`, `trailingComma` with `.editorconfig`. But keeping a `.prettierrc` works. 

```
"semi": false,
"singleQuote": true,
"trailingComma": "all"
```

It doesn't work because I overwrote prettier defaults in VSCode and when `.editorconfig` is present, it doesn't use VSCode but respects a `.prettierrc` file next to `.editorconfig`.

**Comment by steebchen** [comment]
Well, editorconfig does not know about that – it's just about setting some general values – trailingComma etc. is something specific to JavaScript. I think adding a .prettierrc makes sense and put the editorconfig rules into the prettier config.

**Comment by divyenduz** [comment]
> and put the editorconfig rules into the prettier config

Even that won't be required. Prettier merges both so just keeping the `.prettierrc` is enough
