### ISSUE TITLE
Do not start/queue another `check-for-update` run if there are already some waiting

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#696]
If there are already >1 runs in queue, it does not make sense to start more and we should just skip starting more so the queue does not explode when something is hanging with Actions.

**Comment by janpio** [comment]
Another alternative would be to let the jobs time out after x minutes: https://stackoverflow.com/questions/59073731/set-default-timeout-on-github-action-pipeline

**Comment by janpio** [comment]
This is probably not that easy:

https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

- the default for the `timeout-minutes` is 6 hours.
- the "job execution time" limit is also 6 hours 
- that kinda indicates it is the same thing - which would exclude queue time
- so this setting can not help here

**Comment by janpio** [comment]
Ok, quick summary:

- We can not control if a job is queued or not if it is on a schedule
- We could possibly cancel a run when some condition kicks in instead of actually start it to do the work
- The Github action does not seem to have access to when it was queued though
- Should be possible using the API though: https://developer.github.com/v3/actions/workflows/#list-repository-workflows

**Comment by janpio** [comment]
Other potentially relevant GH Actions:
https://github.com/marketplace/actions/workflow-run-cleanup-action
https://github.com/marketplace/actions/cancel-previous-workflow-runs
https://github.com/marketplace/actions/pull-request-workflow-cancel
https://github.com/marketplace/actions/cancel-workflow-runs
https://github.com/marketplace/actions/cancel-workflow-action
https://github.com/marketplace/actions/workflow-conclusion-action
https://github.com/marketplace/actions/workflow-run-cleanup-action
https://github.com/marketplace/actions/cancel-all-previous-workflow-runs
(Can possibly be used as inspiration for code and API usage, even though they do not solve our problem directly)

**Comment by divyenduz** [comment]
https://github.com/softprops/turnstyle

**Comment by millsp** [comment]
Already fixed by `concurrency: check-for-update` in the workflow.
