### ISSUE TITLE
Dependency updates: Run only tests for projects that were updated

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#716]
Example: https://github.com/prisma/e2e-tests/pull/715/files
Updates the dependency for 3 projects.
GH Actions needs to run workflow with tests for _all_ projects.
Confidence in the PR would be the same after running tests for exactly these 3 projects only.

**Comment by divyenduz** [comment]
This can be done in 2 steps:

1. Make a workflow dispatch action that can take arguments of what to test
2. Trigger that from PRs by collecting the changed projects

Not sure if it is worth the effort though, as we don't make too many changes to this repo and it is okay if all the tests run every now and then.

Makes sense for renovate PRs though.

**Comment by janpio** [comment]
Duplicate of https://github.com/prisma/e2e-tests/issues/1746
