### ISSUE TITLE
E2E test for GCP MySQL with SSL

### ISSUE THREAD

**Issue by divyenduz** [prisma/ecosystem-tests#751]
Also serves as an example usage of SSL certs

Prisma docs: https://www.prisma.io/docs/concepts/database-connectors/mysql#configuring-an-ssl-connection

GCP docs: https://cloud.google.com/sql/docs/mysql/configure-ssl-instance

**Comment by divyenduz** [comment]
Update: I and @pantharshit00 couldn't get this to work MySQL 5.7. Harshit is now working on a reproduction, also testing MySQL 8, Postgres and validating if this is a regression.

**Comment by janpio** [comment]
Internal context: https://prisma-company.slack.com/archives/CEYCG2MCN/p1598601957086700
