### ISSUE TITLE
Strip color output from PgBouncer E2E tests

### ISSUE THREAD

**Issue by divyenduz** [prisma/ecosystem-tests#752]
For consistent snapshots across OSes

https://github.com/prisma/e2e-tests/pull/738

**Comment by janpio** [comment]
Why only for pgbouncer then?

**Comment by divyenduz** [comment]
Because no other test has a snapshot i.e. is affected by colors.

**Comment by divyenduz** [comment]
Blocked on https://github.com/prisma/prisma-client-js/issues/885
