### ISSUE TITLE
Update all READMEs to the standard of frameworks/nextjs

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#798]
- [x] Make sure library capitalization etc is correct (NEXTJS => Next.js)
- [x] Properly describe project and its details
- [x] Remove shell scripts that are equal for all projects
- [x] `## How to run this locally` => `## About this project` 

https://github.com/prisma/e2e-tests/blob/dev/frameworks/nextjs/README.md

**Comment by divyenduz** [comment]
Seems to reflect the points mentioned here. Closing.

**Comment by janpio** [comment]
No: https://github.com/prisma/e2e-tests/search?q=How+to+run+this+locally

**Comment by divyenduz** [comment]
Is this just about `frameworks/nextjs` or all of them?

**Comment by janpio** [comment]
This is about all of them, being adapted after the good example of `frameworks/nextjs`

**Comment by janpio** [comment]
Replaced by https://github.com/prisma/e2e-tests/issues/1923
