### ISSUE TITLE
Codesandbox deployment is not identified as CI=true

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#827]
See https://github.com/prisma/e2e-tests/pull/822/files#r487852618

**Comment by divyenduz** [comment]
We concluded that `ci-info` doesn't pick up env vars (like `CI=1`) loaded from `prisma/.env` because `dotenv.config()` is called after checkpoint (and hence `ci-info` is imported) and CI info gets stale/unset env vars. 

Issue: https://github.com/prisma/prisma2-private/issues/102

**Comment by divyenduz** [comment]
This is working now since the underlying issue was fixed. Some logs can be seen [here](https://app.redash.io/prismaio/queries/469381?p_ci=%5B%22true%22%2C%22false%22%5D&p_information=e2e-tests%20platform%20codesandbox%20.env) (internal)
