### ISSUE TITLE
Test community generators

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#850]
- Input on generators to test: https://app.redash.io/prismaio/queries/476639
- Make tests optional or fyi, separate workflow so build status is separate
- (Nexus Plugin Prisma test can also be part of this "fyi" test suite for example)

**Comment by divyenduz** [comment]
What can such a test look like? I guess that will be contextual based on the generator in question. So rough "generic" generator workflow will be something like

1. Create a project with `schema.prisma` capable of generating the generator in question
2. Generate it
3. Somehow test it
4. Make sure that this generator is up to date in the update scripts so we are always testing against the latest version (even canary or equivalent) of this community generator

Enforcing optionality: Run 1-3 in a new job that is not a required job OR run it from a completely separate workflow

**Comment by divyenduz** [comment]
Making this list explicit: 

Glue work: 

- [x] New workflow (define slack message/failure characteristics)

First iteration:

- [x] prisma-dbml-generator

Tier 1 (main implementations of TypeGraphQL, NextJS generators): 

- [x] typegraphql-prisma blocked by https://github.com/MichalLytek/typegraphql-prisma/issues/31
Now blocked by breaking change in the dmmf https://github.com/prisma/prisma-engines/pull/1352. Expected fix next week. 
![image](https://user-images.githubusercontent.com/746482/99567944-14457f00-29cf-11eb-8221-847f8d1473d1.png)

**Comment by janpio** [comment]
Next step: Sync with Devrel what community generators to test.

**Comment by nikolasburk** [comment]
- https://github.com/valentinpalkovic/prisma-json-schema-generator
