### ISSUE TITLE
check-for-update does not take actual start time into account

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#875]
When GH actions is overloaded with tasks, it takes quite some time between when a check-for-updates workflow is scheduled and when it is started. This can lead to multiple runs waiting and then starting at the same time:

![image](https://user-images.githubusercontent.com/183673/95785963-05d0bd00-0cd7-11eb-9e66-bfbb9cfe8067.png)
![image](https://user-images.githubusercontent.com/183673/95785983-0ff2bb80-0cd7-11eb-98c2-d871e36a4857.png)
![image](https://user-images.githubusercontent.com/183673/95786005-1aad5080-0cd7-11eb-8e50-0c2cd012bc0b.png)

It would be great if the script could take the actual time the job was scheduled into account for its duration, not just the start time.

**Comment by millsp** [comment]
Scripts now contain `concurrency: check-for-update` and can not pile up, so this issue could be closed I think.
