### ISSUE TITLE
Add an example using pm2

### ISSUE THREAD

**Issue by Jolg42** [prisma/ecosystem-tests#884]
PM2 is a production process manager for Node.js applications with a built-in load balancer. It allows you to keep applications alive forever, to reload them without downtime and to facilitate common system admin tasks.
https://github.com/Unitech/pm2

It's used a lot to manage Node apps, and it could be useful to have a simple start and stop on all operating systems.

**Comment by Jolg42** [comment]
It could also have a "beforeExit" hook just introduced https://github.com/prisma/prisma/issues/2917#issuecomment-708340112

**Comment by janpio** [comment]
Do we have an example that we can use as a template already?

**Comment by Jolg42** [comment]
@pantharshit00 did some reproduction for pm2 already so he can probably help

**Comment by divyenduz** [comment]
What does this test look like? I can think of 

1. `pm2 start` a node project that uses Prisma
2. Test it while it runs
3. `pm2 stop` it?

(I use pm2 already so a template is not necessary unless we know that Prisma + pm2 needs something special)
